language: csharp
dist: xenial
addons:
  snaps:
    - name: dotnet-sdk
      classic: true
      channel: latest/beta
sudo: required
mono: none
solution: NeverendingTeaShop.sln
script:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet test tests/NeverendingTeaShop.API.Tests
  - dotnet test tests/NeverendingTeaShop.Application.Tests